extends:
  - stylelint-config-hope
rules:
  declaration-block-no-redundant-longhand-properties: true
  media-feature-range-notation: prefix
  no-descending-specificity: null
  # FIXME: stylelint-scss bug
  block-no-redundant-nested-style-rules: null
  # FIXME: stylelint-scss bug
  no-invalid-position-declaration: null
ignoreFiles:
  - "**/*.module.scss"
  - "**/node_modules/**"
  - "**/dist/**"
  - "docs-shared/lib/**"
  - "packages/*/lib/**"
  - "**/.vuepress/.cache/**"
  - "**/.vuepress/.temp/**"
  - "**/.vuepress/dist/**"
